version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth:
    build: ./auth-service
    image: aiyzajunaid/auth-service:latest
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}

  backend:
    build: ./backend-service
    image: aiyzajunaid/backend-service:latest
    ports:
      - "5000:5000"
    depends_on:
      - auth
      - mongo

  frontend:
    build: ./frontend
    image: aiyzajunaid/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
