apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: aiyzajunaid/auth-service:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://aiyzajunaid:3ApzXd.q3Js8w-E@cluster0.qrqa8mi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
